"use client"
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_Component/_navbar/Navbar";
import Foter from "./_Component/_fotter/Foter";
import { store } from "./_store/store";
import { Provider } from "react-redux";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider  store={store}>
        <body className={inter.className }>
          <Navbar />
         < ToastContainer />
          {children}
         
          <Foter />
        </body>
      </Provider>
    </html>
  );
}
